PUT http://localhost:8080/series/temp-1000

###

POST http://localhost:8080/series/temp-1000

{
    "entries": [
        {
            "timestamp": 1,
            "value": 10.0
        },
        {
            "timestamp": 2,
            "value": 20.0
        },
        {
            "timestamp": 4,
            "value": 40.0
        },
        {
            "timestamp": 5,
            "value": 50.0
        }
    ]
}

### 

POST http://localhost:8080/series/temp-1000

{
    "entries": [
        {
            "timestamp": 10,
            "value": 60.0
        },
        {
            "timestamp": 11,
            "value": 70.0
        },
        {
            "timestamp": 16,
            "value": 80.0
        }
    ]
}

### 

POST http://localhost:8080/series/temp-1000

{
    "entries": [
        {
            "timestamp": 21,
            "value": 81.0
        },
        {
            "timestamp": 23,
            "value": 84.0
        },
        {
            "timestamp": 26,
            "value": 90.0
        }
    ]
}

####

GET http://localhost:8080/series/t
    ?from=2019-08-01
    &group_by=hour
    &aggregators=mean
    &limit=1000