name: Release

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Build image
      run: docker build -t whiter4bbit/milliseriesdb:latest .
    - name: Push image (Login)
      run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USER}}" --password-stdin"
    - name: Push image (Push)
      run: docker push whiter4bbit/milliseriesdb:latest      